use_frameworks!

platform :ios, '8.0'

target 'MJKDatabaseExample' do
    pod 'MJExtension', '3.0.17'
    pod 'MJKDatabase', :path => '../' #:git => 'https://github.com/majiakun111/MJKDatabase.git', :tag => '1.0.1'
end
